name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run code quality checks
        run: |
          echo "Запуск проверок качества кода..."
          # Исключаем .git и .github, ищем только в файлах с исходным кодом
          if grep -rnw --exclude-dir=.git --exclude-dir=.github --include=\*.{js,py,txt,css,md} . -e "HACK"; then
            echo "❌ Ошибка: Найдено запрещенное слово 'HACK'!"
            exit 1
          fi
          echo "✅ Код чист, проверки пройдены!"